eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2001/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics